FROM ubuntu:14.04

RUN apt-get update \
	&& apt-get install -y unzip libelf1 curl \
	&& apt-get clean \
	&& rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
	&& curl -SL "https://github.com/facebook/flow/releases/download/v0.30.0/flow-linux64-v0.30.0.zip" -o "flow-linux64-v0.9.2.zip" \
	&& unzip "flow-linux64-v0.9.2.zip" -d /usr/local \
	&& rm "flow-linux64-v0.9.2.zip"

ENV PATH /usr/local/flow:$PATH

WORKDIR /cids/development

CMD ["flow", "check"]
